# This is a basic workflow to help you get started with Actions

name: CD-dev

# Controls when the workflow will run
on:
  # Triggers thse workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prod
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run:  git fetch --unshallow
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.8.1'
          includePrerelease: true
          
      

      # Runs a single command using the runners shell
      - name: cake deploy
        env:
            FEED_URL: '${{ secrets.FEED_URL }}'
            FEED_API_KEY: '${{ FEED_API_KEY }}'
        run:  |
            # make file runnable, might not be necessary
            chmod +x "${GITHUB_WORKSPACE}/build.sh"

            # run script
            "${GITHUB_WORKSPACE}/build.sh --target Deploy"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
